Repository o1-labs/rfcs, pull requests merged in 2023-06, with the labels that each got.

#3 README.md to describe RFCs at O(1) Labs
  README.md
Labels: documentation, enhancement

#4 edits for RFC 0001-template.md
  0001-template.md
Labels: documentation, enhancement

#10 remove extraneous markdown heading since TOC is auto in GitHub
  0001-template.md
Labels: bug

#8 [RFC] Mina Local Network as Docker image
  0004-dockerised-local-network.md
Labels: UX/DX
